# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ForceUpdateInfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ForceUpdateInfo.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x46orceUpdateInfo.proto\"+\n\x0f\x46orceUpdateInfo\x12\x18\n\x10\x66orce_update_url\x18\x01 \x01(\tb\x06proto3'
)




_FORCEUPDATEINFO = _descriptor.Descriptor(
  name='ForceUpdateInfo',
  full_name='ForceUpdateInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='force_update_url', full_name='ForceUpdateInfo.force_update_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['ForceUpdateInfo'] = _FORCEUPDATEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ForceUpdateInfo = _reflection.GeneratedProtocolMessageType('ForceUpdateInfo', (_message.Message,), {
  'DESCRIPTOR' : _FORCEUPDATEINFO,
  '__module__' : 'ForceUpdateInfo_pb2'
  # @@protoc_insertion_point(class_scope:ForceUpdateInfo)
  })
_sym_db.RegisterMessage(ForceUpdateInfo)


# @@protoc_insertion_point(module_scope)
