# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QueryCurrRegionHttpRsp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import ForceUpdateInfo_pb2 as ForceUpdateInfo__pb2
from proto import RegionInfo_pb2 as RegionInfo__pb2
from proto import StopServerInfo_pb2 as StopServerInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='QueryCurrRegionHttpRsp.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cQueryCurrRegionHttpRsp.proto\x1a\x15\x46orceUpdateInfo.proto\x1a\x10RegionInfo.proto\x1a\x14StopServerInfo.proto\"\xa6\x02\n\x16QueryCurrRegionHttpRsp\x12\x0f\n\x07retcode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12 \n\x0bregion_info\x18\x03 \x01(\x0b\x32\x0b.RegionInfo\x12\x19\n\x11\x63lient_secret_key\x18\x0b \x01(\x0c\x12&\n\x1eregion_custom_config_encrypted\x18\x0c \x01(\x0c\x12-\n%client_region_custom_config_encrypted\x18\r \x01(\x0c\x12(\n\x0c\x66orce_update\x18\x04 \x01(\x0b\x32\x10.ForceUpdateInfoH\x00\x12&\n\x0bstop_server\x18\x05 \x01(\x0b\x32\x0f.StopServerInfoH\x00\x42\x08\n\x06\x64\x65tailb\x06proto3'
  ,
  dependencies=[ForceUpdateInfo__pb2.DESCRIPTOR,RegionInfo__pb2.DESCRIPTOR,StopServerInfo__pb2.DESCRIPTOR,])




_QUERYCURRREGIONHTTPRSP = _descriptor.Descriptor(
  name='QueryCurrRegionHttpRsp',
  full_name='QueryCurrRegionHttpRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='retcode', full_name='QueryCurrRegionHttpRsp.retcode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='QueryCurrRegionHttpRsp.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region_info', full_name='QueryCurrRegionHttpRsp.region_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_secret_key', full_name='QueryCurrRegionHttpRsp.client_secret_key', index=3,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region_custom_config_encrypted', full_name='QueryCurrRegionHttpRsp.region_custom_config_encrypted', index=4,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_region_custom_config_encrypted', full_name='QueryCurrRegionHttpRsp.client_region_custom_config_encrypted', index=5,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='force_update', full_name='QueryCurrRegionHttpRsp.force_update', index=6,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stop_server', full_name='QueryCurrRegionHttpRsp.stop_server', index=7,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='detail', full_name='QueryCurrRegionHttpRsp.detail',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=96,
  serialized_end=390,
)

_QUERYCURRREGIONHTTPRSP.fields_by_name['region_info'].message_type = RegionInfo__pb2._REGIONINFO
_QUERYCURRREGIONHTTPRSP.fields_by_name['force_update'].message_type = ForceUpdateInfo__pb2._FORCEUPDATEINFO
_QUERYCURRREGIONHTTPRSP.fields_by_name['stop_server'].message_type = StopServerInfo__pb2._STOPSERVERINFO
_QUERYCURRREGIONHTTPRSP.oneofs_by_name['detail'].fields.append(
  _QUERYCURRREGIONHTTPRSP.fields_by_name['force_update'])
_QUERYCURRREGIONHTTPRSP.fields_by_name['force_update'].containing_oneof = _QUERYCURRREGIONHTTPRSP.oneofs_by_name['detail']
_QUERYCURRREGIONHTTPRSP.oneofs_by_name['detail'].fields.append(
  _QUERYCURRREGIONHTTPRSP.fields_by_name['stop_server'])
_QUERYCURRREGIONHTTPRSP.fields_by_name['stop_server'].containing_oneof = _QUERYCURRREGIONHTTPRSP.oneofs_by_name['detail']
DESCRIPTOR.message_types_by_name['QueryCurrRegionHttpRsp'] = _QUERYCURRREGIONHTTPRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryCurrRegionHttpRsp = _reflection.GeneratedProtocolMessageType('QueryCurrRegionHttpRsp', (_message.Message,), {
  'DESCRIPTOR' : _QUERYCURRREGIONHTTPRSP,
  '__module__' : 'QueryCurrRegionHttpRsp_pb2'
  # @@protoc_insertion_point(class_scope:QueryCurrRegionHttpRsp)
  })
_sym_db.RegisterMessage(QueryCurrRegionHttpRsp)


# @@protoc_insertion_point(module_scope)
