# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RegionInfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import ResVersionConfig_pb2 as ResVersionConfig__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RegionInfo.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10RegionInfo.proto\x1a\x16ResVersionConfig.proto\"\xaf\x06\n\nRegionInfo\x12\x15\n\rgateserver_ip\x18\x01 \x01(\t\x12\x17\n\x0fgateserver_port\x18\x02 \x01(\r\x12\x18\n\x10pay_callback_url\x18\x03 \x01(\t\x12\x11\n\tarea_type\x18\x07 \x01(\t\x12\x14\n\x0cresource_url\x18\x08 \x01(\t\x12\x10\n\x08\x64\x61ta_url\x18\t \x01(\t\x12\x14\n\x0c\x66\x65\x65\x64\x62\x61\x63k_url\x18\n \x01(\t\x12\x14\n\x0c\x62ulletin_url\x18\x0b \x01(\t\x12\x18\n\x10resource_url_bak\x18\x0c \x01(\t\x12\x14\n\x0c\x64\x61ta_url_bak\x18\r \x01(\t\x12\x1b\n\x13\x63lient_data_version\x18\x0e \x01(\r\x12\x14\n\x0chandbook_url\x18\x10 \x01(\t\x12#\n\x1b\x63lient_silence_data_version\x18\x12 \x01(\r\x12\x17\n\x0f\x63lient_data_md5\x18\x13 \x01(\t\x12\x1f\n\x17\x63lient_silence_data_md5\x18\x14 \x01(\t\x12-\n\x12res_version_config\x18\x16 \x01(\x0b\x32\x11.ResVersionConfig\x12\x12\n\nsecret_key\x18\x17 \x01(\x0c\x12\x1e\n\x16official_community_url\x18\x18 \x01(\t\x12\x1d\n\x15\x63lient_version_suffix\x18\x1a \x01(\t\x12%\n\x1d\x63lient_silence_version_suffix\x18\x1b \x01(\t\x12\"\n\x1ause_gateserver_domain_name\x18\x1c \x01(\x08\x12\x1e\n\x16gateserver_domain_name\x18\x1d \x01(\t\x12\x17\n\x0fuser_center_url\x18\x1e \x01(\t\x12\x18\n\x10\x61\x63\x63ount_bind_url\x18\x1f \x01(\t\x12\x11\n\tcdkey_url\x18  \x01(\t\x12\x1a\n\x12privacy_policy_url\x18! \x01(\t\x12\x19\n\x11next_resource_url\x18\" \x01(\t\x12\x32\n\x17next_res_version_config\x18# \x01(\x0b\x32\x11.ResVersionConfig\x12\x10\n\x08game_biz\x18$ \x01(\tb\x06proto3'
  ,
  dependencies=[ResVersionConfig__pb2.DESCRIPTOR,])




_REGIONINFO = _descriptor.Descriptor(
  name='RegionInfo',
  full_name='RegionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gateserver_ip', full_name='RegionInfo.gateserver_ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gateserver_port', full_name='RegionInfo.gateserver_port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pay_callback_url', full_name='RegionInfo.pay_callback_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='area_type', full_name='RegionInfo.area_type', index=3,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resource_url', full_name='RegionInfo.resource_url', index=4,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_url', full_name='RegionInfo.data_url', index=5,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feedback_url', full_name='RegionInfo.feedback_url', index=6,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bulletin_url', full_name='RegionInfo.bulletin_url', index=7,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resource_url_bak', full_name='RegionInfo.resource_url_bak', index=8,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_url_bak', full_name='RegionInfo.data_url_bak', index=9,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_data_version', full_name='RegionInfo.client_data_version', index=10,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='handbook_url', full_name='RegionInfo.handbook_url', index=11,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_silence_data_version', full_name='RegionInfo.client_silence_data_version', index=12,
      number=18, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_data_md5', full_name='RegionInfo.client_data_md5', index=13,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_silence_data_md5', full_name='RegionInfo.client_silence_data_md5', index=14,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='res_version_config', full_name='RegionInfo.res_version_config', index=15,
      number=22, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='secret_key', full_name='RegionInfo.secret_key', index=16,
      number=23, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='official_community_url', full_name='RegionInfo.official_community_url', index=17,
      number=24, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_version_suffix', full_name='RegionInfo.client_version_suffix', index=18,
      number=26, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_silence_version_suffix', full_name='RegionInfo.client_silence_version_suffix', index=19,
      number=27, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_gateserver_domain_name', full_name='RegionInfo.use_gateserver_domain_name', index=20,
      number=28, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gateserver_domain_name', full_name='RegionInfo.gateserver_domain_name', index=21,
      number=29, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_center_url', full_name='RegionInfo.user_center_url', index=22,
      number=30, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='account_bind_url', full_name='RegionInfo.account_bind_url', index=23,
      number=31, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cdkey_url', full_name='RegionInfo.cdkey_url', index=24,
      number=32, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='privacy_policy_url', full_name='RegionInfo.privacy_policy_url', index=25,
      number=33, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='next_resource_url', full_name='RegionInfo.next_resource_url', index=26,
      number=34, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='next_res_version_config', full_name='RegionInfo.next_res_version_config', index=27,
      number=35, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='game_biz', full_name='RegionInfo.game_biz', index=28,
      number=36, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=860,
)

_REGIONINFO.fields_by_name['res_version_config'].message_type = ResVersionConfig__pb2._RESVERSIONCONFIG
_REGIONINFO.fields_by_name['next_res_version_config'].message_type = ResVersionConfig__pb2._RESVERSIONCONFIG
DESCRIPTOR.message_types_by_name['RegionInfo'] = _REGIONINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegionInfo = _reflection.GeneratedProtocolMessageType('RegionInfo', (_message.Message,), {
  'DESCRIPTOR' : _REGIONINFO,
  '__module__' : 'RegionInfo_pb2'
  # @@protoc_insertion_point(class_scope:RegionInfo)
  })
_sym_db.RegisterMessage(RegionInfo)


# @@protoc_insertion_point(module_scope)
