# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StopServerInfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='StopServerInfo.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14StopServerInfo.proto\"b\n\x0eStopServerInfo\x12\x17\n\x0fstop_begin_time\x18\x01 \x01(\r\x12\x15\n\rstop_end_time\x18\x02 \x01(\r\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x13\n\x0b\x63ontent_msg\x18\x04 \x01(\tb\x06proto3'
)




_STOPSERVERINFO = _descriptor.Descriptor(
  name='StopServerInfo',
  full_name='StopServerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stop_begin_time', full_name='StopServerInfo.stop_begin_time', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stop_end_time', full_name='StopServerInfo.stop_end_time', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='StopServerInfo.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content_msg', full_name='StopServerInfo.content_msg', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=122,
)

DESCRIPTOR.message_types_by_name['StopServerInfo'] = _STOPSERVERINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StopServerInfo = _reflection.GeneratedProtocolMessageType('StopServerInfo', (_message.Message,), {
  'DESCRIPTOR' : _STOPSERVERINFO,
  '__module__' : 'StopServerInfo_pb2'
  # @@protoc_insertion_point(class_scope:StopServerInfo)
  })
_sym_db.RegisterMessage(StopServerInfo)


# @@protoc_insertion_point(module_scope)
