name: Query

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: do query
        env:
          URL: ${{ secrets.URL }}
        run: |
          python -m pip install pycryptodome requests
          python main.py
