name: Query

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: do query
        env:
          URL: ${{ secrets.URL }}
        run: |
          python -m pip install pycryptodome requests protobuf==3.19.1
          python main.py

      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ${{github.workspace}}/blk/